const express=require('express')
const bodyParser=require('body-parser')
const cors=require('cors')
const app=express()
const db=require('./config/dataBase')
const clientRouter=require('./routers/clientRouter')
const RestaurateurRouter=require('./routers/restaurateurRouter')
const livreurRouter=require('./routers/livreurRouter')
const restoRouter=require('./routers/restoRouter')
const comRouter=require('./routers/commentRouter')
const categorieRouter=require('./routers/categorieRouter')
const adminRouter=require('./routers/adminRouter')
const menuRouter=require('./routers/menuRouter')
const sousMenuRouter=require('./routers/sousmenuRouter')
const platRouter=require('./routers/platRouter')
const reservRouter=require('./routers/reservationRouter')
const roleRouter=require('./routers/roleRouter')
const userRouter=require('./routers/userRouter')
const { urlencoded } = require('body-parser')
app.get('/',function(req,res){
    res.send('hello world')
})
app.use(cors())
app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(bodyParser.json());
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

app.use('/client',clientRouter)
app.use('/restaurateur',RestaurateurRouter)
app.use('/livreur',livreurRouter)
app.use('/resto',restoRouter)
app.use('/comment',comRouter)
app.use('/categorie',categorieRouter)
app.use('/admin',adminRouter)
app.use('/menu',menuRouter)
app.use('/sousMenu',sousMenuRouter)
app.use('/plat',platRouter)
app.use('/reservation',reservRouter)
app.use('/role',roleRouter)
app.use('/user',userRouter)
app.set("secretkey","RestoServ")//jwt cle prive : utilise au moment du creation du token et du verfication di token (middleware)
app.listen(3200)
console.log('server is running on port 3200')