const express=require('express')
const adminController=require('../controllers/adminController')
const route=express.Router()
const auth=require('../middelwiares/authentification')
// const userController=require('../controllers/clientController')
// route.get('/getAll',auth.validateUser,userController.getAll)
route.post('/login',adminController.authentification)
route.post('/register',adminController.addAdmin)
route.post('/logout',adminController.logOut)
route.post('/refresh/:id',adminController.refreshToken)
route.post('/sendEmail',adminController.sendmail)
route.put('/pushRole/:id',adminController.pushrole)
route.delete('/pullRole/:id',adminController.pullRole)
// route.post('/sendSms',adminController.sendsms)
module.exports=route