const livreurController=require('../controllers/livreurController')
const express=require('express')
const route=express.Router()
route.post('/login',livreurController.authentification)
route.post('/logout',livreurController.logOut)
route.post('/addLivreur',livreurController.addlivreur)
route.get('/getAll',livreurController.getAll)
route.get('/getById/:id',livreurController.getById)
route.put('/update/:id',livreurController.update)
route.delete('/delete/:id',livreurController.delete)
route.post('/refresh/:id',livreurController.refreshToken)
route.put('/pushResto/:id',livreurController.pushResto)
route.put('/pullResto/:id',livreurController.pullResto)
module.exports=route