const express=require('express')
const restaurateurController=require('../controllers/restaurateurController')
const route=express.Router()
route.post('/login',restaurateurController.authentification)
route.post('/logout',restaurateurController.logOut)
route.post('/register',restaurateurController.addRestaurateur)
route.get('/getAll',restaurateurController.getAll)
route.get('/getById/:id',restaurateurController.getById)
route.put('/update/:id',restaurateurController.update)
route.delete('/delete/:id',restaurateurController.delete)
route.put('/pushResto/:id',restaurateurController.pushResto)
route.delete('/pullResto/:id',restaurateurController.pullResto)
route.post('/refresh/:id',restaurateurController.refreshToken)
module.exports=route
